### ISSUE TITLE
OLS vs ontobee

### ISSUE THREAD

**Issue by drmarkreuter** [allysonlister/swo#39]
![ols-vs-ontobee](https://user-images.githubusercontent.com/26660961/68386811-c60f6600-0154-11ea-85bd-78aa85208ad4.png)
Possibly a stupid question, but why can't I see the SWO updates on the OLS site? A lot of my tooling relies on the OLS platform rather than the ontobee platform (JSON calls, that sort of thing). Not really an issue, just curious about the difference. Many thanks!

**Comment by allysonlister** [comment]
Hi @drmarkreuter :-) Thanks for the question. There was a bug with the OLS code that needed fixing in order to display the latest version of SWO. They are working on it, but it hasn't rolled out yet. They've been very responsive - we just need to give them a little bit more time...!

Please see this ticket I made on the OLS tracker in regards to SWO 1.7:
https://github.com/EBISPOT/OLS/issues/294

Thanks! :) Ally

**Comment by allysonlister** [comment]
I should point out that both BioPortal and Ontobee have the new version already. It shouldn't be long before OLS' update is pushed and we see 1.7 there too. I'll update and then close this ticket when it's working over at OLS.

**Comment by allysonlister** [comment]
Or, perhaps, do you need me to submit some new information about SWO separate from the OWL file? Thanks!

**Comment by allysonlister** [comment]
Please note that SWO 1.7 is now indexed in OLS - https://www.ebi.ac.uk/ols/ontologies/swo :-)

thanks again, and please re-open if you have any issues / questions!
