### ISSUE TITLE
3 types of software under SWO are also "data items" - this is a problem

### ISSUE THREAD

**Issue by rduerr** [allysonlister/swo#6]
We are developing a registry of (among other things) Earth science software and would like to be compatible with the OBO Foundry.  As such, we would like to re-use as many terms as possible.  We would use the SWO term for software but need it to be compatible with the sdgio ontologies resource - since softwware is a resource that can provide benefit to users.  However, 3 of the many types of software under the software item include an axiom about being a "data item".  This causes a logic error.  The software packages are:

SAFE
Ringo
Rama

Would it be possible to remove these axioms?  Also, I note that we would likely be adding a large number of subclasses for other Earth science related software packages.  I don't know if you would prefer them directly added to SWO or kept in our own ontology.

Thank you!

**Comment by allysonlister** [comment]
Thanks for contacting us! I'd love to work together to sort out these issues so that you can use SWO. I am on vacation today, but am back at work next week, so I will provide a more thorough answer to the specific questions on those three classes next week. (We are fully volunteer managed, as we currently have no specific funding for SWO.) FYI I've also been planning a point release to improve the build procedure for SWO and to modify how we reference EDAM (rather than import all of it, we will likely just reference those parts that are required for our ontology and import those via MIREOT / Ontofox procedures). This will create a more streamlined SWO that will be easier to maintain and use. This shouldn't affect how you use it, as these will mainly be behind-the-scenes changes, but I could incorporate changes you request at the same time.

I would be happy to talk with you about the possibility of adding new terms to SWO (versus keeping them in their own ontology), and you can make the best choice for you. Let me take a closer look at your request next week, and then I'll get back to you again. 

Best wishes,
Allyson

**Comment by allysonlister** [comment]
I've been making changes to SWO for the new release, and would like to find out more about this issue, if it still persists in the latest developmental copy. Please could you download https://github.com/allysonlister/swo/blob/master/dev/ontology/swo-merged.owl and let me know if this new version of SWO works? I don't see any particular axioms relating to 'data item' in either the previous release or current working file:
![ringo](https://user-images.githubusercontent.com/143586/65182422-2b9a7c80-da59-11e9-8c47-38cab2baddfc.png)
If you can provide more information, I'll try to get things sorted out for you.

Thanks!

**Comment by rduerr** [comment]
Interesting!  I agree that the new file referenced above doesn't have that problem; however I downloaded the file at http://purl.obolibrary.org/obo/swo.owl again today and it does!  Maybe the redirect is pointing to an older release?

<img width="1062" alt="Screen Shot 2019-09-18 at 4 23 20 PM" src="https://user-images.githubusercontent.com/1544892/65191309-c599ff00-da30-11e9-8200-7db204df9840.png">

**Comment by allysonlister** [comment]
Good morning!

The file i referenced above is the latest, but it is a pre release. The one you downloaded at http://purl.obolibrary.org/obo/swo.owl is still the old release. I'm going through tickets and updating this development version (which I linked in my email), then should build a release in a week or so, after all of these are resolved.

Thanks, Allyson

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by allysonlister** [comment]
It sounds like the latest updates have resolved this problem. Please let me know if you have any further questions. In the meantime, I will close this issue.

The changes will be reflected in the release files soon - after I complete all of the updates linked to this milestone (https://github.com/allysonlister/swo/milestone/1) I'll be building the release. Thanks!
